language: java
script: "cd languages/Natlab; ant test"
branches:
  only:
    - master
    - develop
notifications:
  email:
    recipients:
      - mclab@sable.mcgill.ca
    on_success: change
    on_failure: always
